name: steganographic
description: An app that demos steganography algorithms

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization:

  # state management
  flutter_bloc: ^8.1.3

  # utils
  intl: 0.18.0
  copy_with_extension: ^5.0.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_loco_translations: 1.0.0+2
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
