name: steganographic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization:

  # utils
  intl: 0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_loco_translations: 1.0.0+2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
